# Generated by Django 4.1.7 on 2023-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripusers",
            name="interested",
            field=models.BooleanField(default=True),
        ),
    ]
