# Generated by Django 4.1.7 on 2023-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_tripusers_interested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripusers",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
