# Generated by Django 4.1.7 on 2023-05-12 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0004_alter_trip_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="users",
            field=models.ManyToManyField(
                related_name="trips_users",
                through="trips.TripUsers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
