# Generated by Django 4.1.7 on 2023-05-12 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0008_alter_tripusers_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tripusers",
            unique_together=set(),
        ),
    ]
