# Generated by Django 4.1.7 on 2023-05-12 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0009_alter_tripusers_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tripusers",
            unique_together={("user", "trip")},
        ),
    ]
