# Generated by Django 4.1.7 on 2023-05-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0010_alter_tripusers_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="splitwise_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
