# Generated by Django 4.1.7 on 2023-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_users_access_token_users_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="splitwise_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
